parameters:
  render.engine_by_extension: ~ # provided by compiler pass

  render.application_paths:
  - app/all

services:
  _defaults:
    autowire: true

  ICanBoogie\Render\PHPEngine:
    tags:
    - { name: 'render.engine' }
    - { name: 'render.extension', extension: '.php' }
    - { name: 'render.extension', extension: '.phtml' }

  ICanBoogie\Render\EngineProvider\Container:
    arguments:
      $container: !tagged_locator { tag: render.engine }
      $mapping: '%render.engine_by_extension%'

  ICanBoogie\Render\EngineProvider:
    alias: ICanBoogie\Render\EngineProvider\Container

  #

  ICanBoogie\Render\BasicTemplateResolver:
    $paths:
      - app/all/templates

#  ICanBoogie\Binding\Render\ApplicationTemplateResolver:
#    decorates: ICanBoogie\Render\BasicTemplateResolver
#    arguments:
#      $paths: '%render.application_paths%'

  ICanBoogie\Render\TemplateResolver:
    alias: ICanBoogie\Render\BasicTemplateResolver

  #

  ICanBoogie\Render\Renderer:
    public: true
