parameters:
  render.engine_by_extension: ~ # provided by compiler pass
  render.extensions: ~ # provided by compiler pass

  # Used by the template resolver to search files matching template names.
  render.template_paths:
  - app/all/templates # Should be first to be able to override modules templates.

services:
  _defaults:
    autowire: true

  # Engines

  ICanBoogie\Render\PHPEngine:
    tags:
    - { name: 'render.engine' }
    - { name: 'render.extension', extension: '.phtml' }
    - { name: 'render.extension', extension: '.php' }

  ICanBoogie\Render\EngineProvider\Container:
    arguments:
      $container: !tagged_locator { tag: render.engine }
      $mapping: '%render.engine_by_extension%'

  ICanBoogie\Render\EngineProvider:
    alias: ICanBoogie\Render\EngineProvider\Container

  # Template resolver

  ICanBoogie\Render\TemplateResolver:
    alias: ICanBoogie\Render\BasicTemplateResolver

  ICanBoogie\Render\BasicTemplateResolver:
    $paths: '%render.template_paths%'

  ICanBoogie\Render\TemplateResolver\Memoize:
    decorates: ICanBoogie\Render\TemplateResolver
    decoration_priority: -100

  # Renderer

  ICanBoogie\Render\Renderer:
    public: true
